name:                cc
version:             0.1.0.0
github:              "lopezfjose/cc"
license:             BSD3
author:              "Jose Fernando Lopez Fernandez"
maintainer:          "josefernando.lopezfernandez@snhu.edu"
copyright:           "Copyright (c) 2018 Jose Fernando Lopez Fernandez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lopezfjose/cc#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers

library:
  source-dirs: src

executables:
  cc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cc

tests:
  cc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cc
